### ISSUE TITLE
Bug: found a problematic VectorDrawable icon

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [mistamek/Android-drawable-preview-plugin#10] opened 2019-01-09 14:34 UTC
Here's what I see:

![image](https://user-images.githubusercontent.com/5357526/50905816-504f4680-142c-11e9-98a6-5951d4212002.png)

Attached the problematic file.

[ic_call_end_white_24dp.zip](https://github.com/mistamek/Android-drawable-preview-plugin/files/2741245/ic_call_end_white_24dp.zip)

**Comment by mistamek** [comment] 2019-01-16 14:10
Hi, I am terribly sorry for the long answer. For rendering vector icons, I use the JetBrains library. I will look at what could be the problem, but I do not guarantee that I can fix it.

**Comment by AndroidDeveloperLB** [comment] 2019-01-16 14:11
I think it's an IDE issue. Reported here too about a similar file:

https://issuetracker.google.com/issues/122785997

**Comment by AndroidDeveloperLB** [comment] 2019-01-16 14:12
If it's JetBrains , maybe you could give them more information, here:

https://youtrack.jetbrains.com/newIssue?draftId=25-2224393

**Comment by mistamek** [comment] 2019-01-16 18:59
No, this is not an IDE problem. Most likely the problem is that the vector is rendered to a small icon and, because of this, a tint comes out. Tomorrow I will try to render the vector in higher resolution, and then compress it.

**Comment by AndroidDeveloperLB** [comment] 2019-01-16 19:06
Why would a black tint come out for a vectorized image that has only red/white color ?
And only in some part of it...
It's a vector. It should look fine no matter how small/large it is.
And since it occurs outside of the scope of your plugin, I think it is related to the IDE in one way or another.

**Comment by mistamek** [comment] 2019-01-17 09:38
Well, I have no idea why :) But definitely agree that it should look the same in different sizes. Btw did not notice that the same problem was in the xml layout. In that case, let's wait for a response from Google / JetBrains.

**Comment by AndroidDeveloperLB** [comment] 2019-01-17 11:28
OK thank you.
Maybe we should close it, then?
Your choice :)

**Comment by mistamek** [comment] 2019-01-17 11:42
Ok, let's close it for now. If additional actions will be required, I will correct it.

**Closed as completed by mistamek** 2019-01-17 11:42 UTC

**Comment by AndroidDeveloperLB** [comment] 2019-01-17 11:48
OK thank you.
Could you please report about it on the Jetbrains forum, though? I only wrote about it on the issue tracker...
